export default {
  index: 'Overview',
  '--- Core': { type: 'separator', title: 'Core' },
  health: 'Health',
  auth: 'Authentication',
  users: 'Users',
  profiles: 'Profiles',
  '--- Names & Search': { type: 'separator', title: 'Names & Search' },
  names: 'Names',
  search: 'Search',
  '--- Marketplace': { type: 'separator', title: 'Marketplace' },
  listings: 'Listings',
  offers: 'Offers',
  orders: 'Orders',
  sales: 'Sales',
  'brokered-listings': 'Brokered Listings',
  cart: 'Cart',
  '--- Social': { type: 'separator', title: 'Social' },
  watchlist: 'Watchlist',
  clubs: 'Clubs',
  votes: 'Votes',
  notifications: 'Notifications',
  activity: 'Activity',
  '--- Discovery': { type: 'separator', title: 'Discovery' },
  trending: 'Trending',
  leaderboard: 'Leaderboard',
  'awards-leaderboard': 'Awards Leaderboard',
  recommendations: 'Recommendations',
  'ai-recommendations': 'AI Recommendations',
  'ai-search-semantic': 'AI Search (Semantic)',
  'ai-search-related': 'AI Search (Related)',
  '--- Analytics': { type: 'separator', title: 'Analytics' },
  analytics: 'Analytics',
  charts: 'Charts',
  'google-metrics': 'Google Metrics',
  'user-insights': 'User Insights',
  '--- System': { type: 'separator', title: 'System' },
  verification: 'Verification',
  legends: 'Legends',
  personas: 'Personas',
  poap: 'POAP',
  'ens-roles': 'ENS Roles',
  subgraph: 'Subgraph',
  websocket: 'WebSocket',
}
